#!/bin/sh
#
# kermit-mqrecv      Custom queue consumer using the mcollective framework
#
# chkconfig: - 95 5
# description: Enable the receiver on a custom AMQP queue set with Mcollective
#

### BEGIN INIT INFO
# Provides:          kermit-mqrecv 
# Required-Start:    $network
# Required-Stop:     $network
# Description:       Queue consumer 
# Short-Description: Custom queue consumer using the mcollective framework 
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
NAME=recvctl.rb
CONTROL=/usr/local/bin/kermit/queue/${NAME}
DESC=kermit-mqrecv
ROTATE_SUFFIX=

LOCK_FILE=/var/lock/subsys/$NAME

RETVAL=0
set -e

start_mqrecv () {
    set +e
    OUTPUT=$($CONTROL start) 
    echo $OUTPUT | grep -q 'ERROR' 
    STARTSTATUS=$?
    set -e
    case "$STARTSTATUS" in
        1)
            echo SUCCESS
            if [ -n "$LOCK_FILE" ] ; then
                touch $LOCK_FILE
            fi
            RETVAL=0
            ;;
        *)
            echo FAILED
            echo $OUTPUT
            RETVAL=1
            ;;
    esac
}

stop_mqrecv () {
        set +e
        $CONTROL stop
        RETVAL=$?
        set -e
        if [ $RETVAL = 0 ] ; then
            echo SUCCESS
            if [ -n "$LOCK_FILE" ] ; then
                rm -f $LOCK_FILE
            fi
        else
            echo FAILED
        fi
}

status_mqrecv() {
    set +e
    OUTPUT=$($CONTROL status)
    echo $OUTPUT | grep -q 'no instances running' 
    if [ $? = 0 ] ; then
        RETVAL=3
    fi
    echo $OUTPUT
    set -e
}

restart_mqrecv() {
    stop_mqrecv
    start_mqrecv
}

case "$1" in
    start)
        echo -n "Starting $DESC: "
        start_mqrecv
        ;;
    stop)
        echo -n "Stopping $DESC: "
        stop_mqrecv
        ;;
    restart)
        restart_mqrecv
        ;;
    status)
        status_mqrecv
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}" >&2
        RETVAL=1
        ;;
esac

exit $RETVAL
